[server]
maxUploadSize = 50
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = false

[global]
dataFrameSerialization = "legacy"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showErrorDetails = false
toolbarMode = "minimal"
